{% set version = '1.4.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tibble
  version: {{ version|replace("-", "_") }}

source:
  fn: tibble_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tibble_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tibble/tibble_{{ version }}.tar.gz
  sha256: 11670353ff7059a55066dd075d1534d6a27bc5c3583fb9bc291bf750a75c5b17

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-crayon
    - r-pillar >=1.1.0
    - r-rlang
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-cli
    - r-crayon
    - r-pillar >=1.1.0
    - r-rlang

test:
  commands:
    - $R -e "library('tibble')"           # [not win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
  home: http://tibble.tidyverse.org/, https://github.com/tidyverse/tibble
  license: MIT
  summary: Provides a 'tbl_df' class (the 'tibble') that provides stricter checking and better
    formatting than the traditional data frame.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
