travis:
  secure:
    BINSTAR_TOKEN: TdIIYifmShFtR/fyWZHDp1FPwcPld3FrtTvbpRaTjnGYwVj1lreDzjSAo5MGU8zA8isLtf3HTxagjZ1/c009P95rNnWTgZg2T44D4h26jrUFli9X5wnAAYYdxUDAyyTS7PpIo6K30+v+ZTK6Bb+TjJBfN+5ofxGxPj4mxPVYBvyF1R88pDRjy/JtPq6PTHpla6mlShBfWg55zX9WNel/8sdRPK6KWEBp3o3A16xPVa/nEm+hce7YKcZNKkWv0lv2cCrQgAADJ8VwsjJVFnjdBZQvzQoUCV53FpsOBmwMsonaQlL6HIW/dvDncSvgwAQjcLw4qWRnDSyv5bC6IJt923xHjUMvR6PfMELxbURendBmVq3zw//aPTImaSFz3LqEvdiabdNKB0u4/8k6cc6EyGcAWcFFaGyxg6T8FyWPWx6a/LUskfGvCf/EW9mUiBsNl/EaSKhymyeMZuYLuyTtZtigjIcCvu8BOraDQtbJOhj2bz/kQQnlUG6eZAqYutjGFDgSAIhwVHakeZVxRkHBowHGgSWpvowJ4eY/7Y//XJEqtQMMgeYd1t34Vuu7socvw2A2XVpJTie3BPiyubjg5HqeI5nKuYJl52l7YePvi7WynOmDx+tfcoTvRZ2wXRcFxXlsIbF84QfT9WRqWXrmH8lIGs6Jw07BWfdejVjYOw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
